create table if not exists public.enterprise_leads (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  company text not null check (char_length(company) between 1 and 160),
  email text not null check (char_length(email) between 3 and 254),
  created_at timestamptz not null default now()
);

alter table public.enterprise_leads enable row level security;
grant insert on table public.enterprise_leads to anon;
grant usage, select on sequence public.enterprise_leads_id_seq to anon;

drop policy if exists "Anyone can submit an enterprise lead" on public.enterprise_leads;
create policy "Anyone can submit an enterprise lead"
  on public.enterprise_leads for insert to anon with check (true);
